# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "[[CHANGEME]]")
    build_app(scheme: "[[CHANGEME]]")
    upload_to_app_store(
        skip_screenshots: true,
        submission_information: {
            export_compliance_platform: 'ios',
            export_compliance_compliance_required: false,
            export_compliance_encryption_updated: false,
            export_compliance_app_type: nil,
            export_compliance_uses_encryption: false,
            export_compliance_is_exempt: false,
            export_compliance_contains_third_party_cryptography: false,
            export_compliance_contains_proprietary_cryptography: false,
            export_compliance_available_on_french_store: false
        })
    notification(subtitle: "Completed", message: "Uploaded to Appstore")
    upload_symbols_to_crashlytics(binary_path:"./fabric/upload-symbols", dsym_path: "./[[CHANGEME]].app.dSYM.zip")
  end

  desc "Push to testflight"
  lane :beta do
    increment_build_number(xcodeproj: "[[CHANGEME]].xcodeproj")
    build_app(scheme: "[[CHANGEME]]")
    upload_to_testflight(distribute_external: true, groups: "Public testers")
    notification(subtitle: "Completed", message: "Uploaded to testflight")
    upload_symbols_to_crashlytics(binary_path:"./fabric/upload-symbols", dsym_path: "./[[CHANGEME]].app.dSYM.zip")
  end
end
